import type { Metadata } from "next";
import { inter, roboto_mono} from './fonts'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={roboto_mono.className}>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
